rule_files:
  - 'rules.yaml'
global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
#localhost
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
alerting:
  alertmanagers:
  - static_configs:
    - targets: [ 'alertmanager:9093' ]