global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'
  routes:
    # - match:
    #     severity: critical
    #   receiver: 'pagerduty'
    - match:
        severity: critical
      receiver: 'email-notifications'
receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'sabit_mubarik@yahoo.com'
        from: 'sabit@uney.com'
        smarthost: 'smtp.gmail.com:587'
#        smarthost: 'https://uney.com'
        auth_username: 'sabit@uney.com'
        auth_password: 'kspl gmsv puit vkhh'        
#        auth_password: "wjrp rlnw pxmw qebl"
#        auth_password: '{{ .Env.ALERTMANAGER_SMTP_PASSWORD }}'
#        require_tls: true
        send_resolved: true
#  - name: 'pagerduty'
#    pagerduty_configs:
#      - service_key: 'your-pagerduty-service-key'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']