# Fluent Bit Helm Chart Configuration
# This configuration is optimized to handle any type of log format and enrich logs with Kubernetes metadata.

kind: DaemonSet

image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: "2.0.11"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

rbac:
  create: true

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 2020

resources: {}
  # limits:
  #   cpu: "500m"
  #   memory: "512Mi"
  # requests:
  #   cpu: "100m"
  #   memory: "128Mi"

livenessProbe:
  httpGet:
    path: /
    port: 2020

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: 2020

nodeSelector: {}

tolerations: []

affinity: {}

# Fluent Bit Configuration
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 10MB
        Skip_Long_Lines On
        DB /var/log/flb_kube.db
        Ignore_Older 1h
        Refresh_Interval 10

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name modify
        Match *
        Add log_type kubernetes

  outputs: |
    [OUTPUT]
        Name es
        Match *
        Host 16.162.179.143
        Port 9200
        Logstash_Format On
        Logstash_Prefix kchat-dev
        Retry_Limit False
        Suppress_Type_Name On
        Buffer_Size 10MB
        Replace_Dots On

  customParsers: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
        Decode_Field_As json log

    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep On

    [PARSER]
        Name json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

    [PARSER]
        Name multiline
        Format regex
        Regex /^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$/
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep On

volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/conf

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true

command:
  - /fluent-bit/bin/fluent-bit

args:
  - --workdir=/fluent-bit/etc
  - --config=/fluent-bit/etc/conf/fluent-bit.conf

logLevel: info